/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.Pokosenko.RegistrationFrame;

import by.Pokosenko.Message.Message;
import by.Pokosenko.Utils.Actions;

import javax.swing.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 *
 * @author Vladislav
 */
public class RegistrationFrame extends javax.swing.JFrame {

    public Socket socket=null;
    public ObjectOutputStream outputStream;
    /**
     * Creates new form RegistrationWindow
     */
    public RegistrationFrame(Socket socket) throws IOException {
        this.socket=socket;
        outputStream=new ObjectOutputStream(socket.getOutputStream());

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrateNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RegistrateLoginField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RegistratePasswordField = new javax.swing.JPasswordField();
        ToRegistrateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("League Gothic", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Имя пользователя");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 65, -1, 53));

        RegistrateNameField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        getContentPane().add(RegistrateNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 290, 32));

        jLabel2.setFont(new java.awt.Font("League Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Логин");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        RegistrateLoginField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        getContentPane().add(RegistrateLoginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 290, 30));

        jLabel3.setFont(new java.awt.Font("League Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Пароль");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, -1));

        RegistratePasswordField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        getContentPane().add(RegistratePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 290, 30));

        ToRegistrateButton.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        ToRegistrateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vladislav\\Desktop\\регистрация2.jpg")); // NOI18N
        ToRegistrateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToRegistrateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ToRegistrateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vladislav\\Desktop\\фвфы.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void ToRegistrateButtonMouseClicked(java.awt.event.MouseEvent evt) {
        try{

        if(RegistrateNameField.getText().length()==0||
                RegistratePasswordField.getText().length()==0||
                RegistrateLoginField.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Пожалуйста,заполните все поля для регистрации");
        }else {
            String login = RegistrateLoginField.getText();
            String password = RegistratePasswordField.getText();
            System.out.println("Мы может отпрвлять серверу строку");

            outputStream.writeObject(new Message(Actions.Registration));

        }
            } catch (IOException e) {
                e.printStackTrace();
            }




    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField RegistrateLoginField;
    private javax.swing.JTextField RegistrateNameField;
    private javax.swing.JPasswordField RegistratePasswordField;
    private javax.swing.JButton ToRegistrateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration
}
